In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os


In [3]:
os.chdir ("C:\\Noble\\Training\\Top Mentor\\Training\\Data Set\\")
df1= pd.read_excel("Data Preprocessing Data File.xlsx")	
print (df1)


   Country   Age   Salary  Purchased 
0   France   44.0  72000.0         No
1    Spain   27.0  48000.0        Yes
2  Germany    NaN  54000.0         No
3    Spain   39.0      NaN         No
4  Germany    NaN  64000.0        Yes
5   France   35.0  58000.0        Yes
6    Spain   39.0  52000.0         No
7   France   48.0      NaN        Yes
8  Germany   50.0  83000.0         No
9   France   37.0  67000.0        Yes


In [6]:
x = df1.iloc [:,0:-1].values
x

array([['France ', 44.0, 72000.0],
       ['Spain ', 27.0, 48000.0],
       ['Germany ', nan, 54000.0],
       ['Spain ', 39.0, nan],
       ['Germany ', nan, 64000.0],
       ['France ', 35.0, 58000.0],
       ['Spain ', 39.0, 52000.0],
       ['France ', 48.0, nan],
       ['Germany ', 50.0, 83000.0],
       ['France ', 37.0, 67000.0]], dtype=object)

In [8]:
y = df1.iloc [:,3].values
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [9]:
x

array([['France ', 44.0, 72000.0],
       ['Spain ', 27.0, 48000.0],
       ['Germany ', nan, 54000.0],
       ['Spain ', 39.0, nan],
       ['Germany ', nan, 64000.0],
       ['France ', 35.0, 58000.0],
       ['Spain ', 39.0, 52000.0],
       ['France ', 48.0, nan],
       ['Germany ', 50.0, 83000.0],
       ['France ', 37.0, 67000.0]], dtype=object)

In [10]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(x[:,1:3])
x [:,1:3]= imputer.transform(x[:,1:3])
print (x)


In [21]:
from sklearn.impute import SimpleImputer
imp= SimpleImputer(missing_values = np.nan,strategy='mean')
im = imp.fit(x[:,1:3])
x[:,1:3]=im.transform(x[:,1:3])
x

array([['France ', 44.0, 72000.0],
       ['Spain ', 27.0, 48000.0],
       ['Germany ', 39.875, 54000.0],
       ['Spain ', 39.0, 62250.0],
       ['Germany ', 39.875, 64000.0],
       ['France ', 35.0, 58000.0],
       ['Spain ', 39.0, 52000.0],
       ['France ', 48.0, 62250.0],
       ['Germany ', 50.0, 83000.0],
       ['France ', 37.0, 67000.0]], dtype=object)

In [25]:
print (type(x[1][0]))

<class 'str'>


In [ ]:
from sklearn.preprocessing import LabelEncoder
label_x = LabelEncoder()
x[:,0]= label_x.fit_transform(x[:,0])
print (x)


In [31]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
x[:,0]=le.fit_transform(x[:,0])
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 39.875, 54000.0],
       [2, 39.0, 62250.0],
       [1, 39.875, 64000.0],
       [0, 35.0, 58000.0],
       [2, 39.0, 52000.0],
       [0, 48.0, 62250.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [29]:
x

array([['France ', 44.0, 72000.0],
       ['Spain ', 27.0, 48000.0],
       ['Germany ', 39.875, 54000.0],
       ['Spain ', 39.0, 62250.0],
       ['Germany ', 39.875, 64000.0],
       ['France ', 35.0, 58000.0],
       ['Spain ', 39.0, 52000.0],
       ['France ', 48.0, 62250.0],
       ['Germany ', 50.0, 83000.0],
       ['France ', 37.0, 67000.0]], dtype=object)

In [32]:
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 39.875, 54000.0],
       [2, 39.0, 62250.0],
       [1, 39.875, 64000.0],
       [0, 35.0, 58000.0],
       [2, 39.0, 52000.0],
       [0, 48.0, 62250.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))
print (x)


In [37]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('onehot',OneHotEncoder(),[0])], remainder = 'passthrough')
x1= np.array(ct.fit_transform(x))
x1

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 39.875, 54000.0],
       [0.0, 0.0, 1.0, 39.0, 62250.0],
       [0.0, 1.0, 0.0, 39.875, 64000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 39.0, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 62250.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [38]:
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 39.875, 54000.0],
       [2, 39.0, 62250.0],
       [1, 39.875, 64000.0],
       [0, 35.0, 58000.0],
       [2, 39.0, 52000.0],
       [0, 48.0, 62250.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [39]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [ ]:
label_y = LabelEncoder()
y = label_y.fit_transform(y)
print (y)


In [40]:
y_le= LabelEncoder()
y=y_le.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
from sklearn.preprocessing import StandardScaler
std_sca= StandardScaler()
x_STD = std_sca.fit_transform(x)
print (pd.DataFrame(x_STD))


In [45]:
from sklearn.preprocessing import StandardScaler
ss= StandardScaler()
ss_x1= ss.fit_transform(x1)
ss_x1

array([[ 1.22474487, -0.65465367, -0.65465367,  0.66491189,  1.00270654],
       [-0.81649658, -0.65465367,  1.52752523, -2.07533106, -1.46549418],
       [-0.81649658,  1.52752523, -0.65465367,  0.        , -0.848444  ],
       [-0.81649658, -0.65465367,  1.52752523, -0.14104192,  0.        ],
       [-0.81649658,  1.52752523, -0.65465367,  0.        ,  0.17997297],
       [ 1.22474487, -0.65465367, -0.65465367, -0.78580497, -0.43707721],
       [-0.81649658, -0.65465367,  1.52752523, -0.14104192, -1.05412739],
       [ 1.22474487, -0.65465367, -0.65465367,  1.30967494,  0.        ],
       [-0.81649658,  1.52752523, -0.65465367,  1.63205647,  2.13396521],
       [ 1.22474487, -0.65465367, -0.65465367, -0.46342344,  0.48849806]])

In [43]:
x1

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 39.875, 54000.0],
       [0.0, 0.0, 1.0, 39.0, 62250.0],
       [0.0, 1.0, 0.0, 39.875, 64000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 39.0, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 62250.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [47]:
from sklearn.preprocessing import Normalizer
nr= Normalizer()
nr_x1= nr.fit_transform(x1)
pd.DataFrame(nr_x1)

0         1         2         3    4
0  0.000014  0.000000  0.000000  0.000611  1.0
1  0.000000  0.000000  0.000021  0.000562  1.0
2  0.000000  0.000019  0.000000  0.000738  1.0
3  0.000000  0.000000  0.000016  0.000627  1.0
4  0.000000  0.000016  0.000000  0.000623  1.0
5  0.000017  0.000000  0.000000  0.000603  1.0
6  0.000000  0.000000  0.000019  0.000750  1.0
7  0.000016  0.000000  0.000000  0.000771  1.0
8  0.000000  0.000012  0.000000  0.000602  1.0
9  0.000015  0.000000  0.000000  0.000552  1.0

In [48]:
from sklearn.preprocessing import MinMaxScaler
ms= MinMaxScaler()
ms_x1= ms.fit_transform(x1)
pd.DataFrame(ms_x1)

0    1    2         3         4
0  1.0  0.0  0.0  0.739130  0.685714
1  0.0  0.0  1.0  0.000000  0.000000
2  0.0  1.0  0.0  0.559783  0.171429
3  0.0  0.0  1.0  0.521739  0.407143
4  0.0  1.0  0.0  0.559783  0.457143
5  1.0  0.0  0.0  0.347826  0.285714
6  0.0  0.0  1.0  0.521739  0.114286
7  1.0  0.0  0.0  0.913043  0.407143
8  0.0  1.0  0.0  1.000000  1.000000
9  1.0  0.0  0.0  0.434783  0.542857

In [49]:
df1

Country   Age   Salary  Purchased 
0   France   44.0  72000.0         No
1    Spain   27.0  48000.0        Yes
2  Germany    NaN  54000.0         No
3    Spain   39.0      NaN         No
4  Germany    NaN  64000.0        Yes
5   France   35.0  58000.0        Yes
6    Spain   39.0  52000.0         No
7   France   48.0      NaN        Yes
8  Germany   50.0  83000.0         No
9   France   37.0  67000.0        Yes

In [51]:
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 39.875, 54000.0],
       [2, 39.0, 62250.0],
       [1, 39.875, 64000.0],
       [0, 35.0, 58000.0],
       [2, 39.0, 52000.0],
       [0, 48.0, 62250.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [52]:
pd.DataFrame(ss_x1)

0         1         2         3         4
0  1.224745 -0.654654 -0.654654  0.664912  1.002707
1 -0.816497 -0.654654  1.527525 -2.075331 -1.465494
2 -0.816497  1.527525 -0.654654  0.000000 -0.848444
3 -0.816497 -0.654654  1.527525 -0.141042  0.000000
4 -0.816497  1.527525 -0.654654  0.000000  0.179973
5  1.224745 -0.654654 -0.654654 -0.785805 -0.437077
6 -0.816497 -0.654654  1.527525 -0.141042 -1.054127
7  1.224745 -0.654654 -0.654654  1.309675  0.000000
8 -0.816497  1.527525 -0.654654  1.632056  2.133965
9  1.224745 -0.654654 -0.654654 -0.463423  0.488498